--- #=-==-=--=-=-==-=-=--=-=-=-=-=-=-=-==-=-=-#
-- #          <SisLoja - DataBase>             #
-- #    Copyright (C) <2023-2023> <CL-Dev>     #
-- #		                                   #
-- #       | C | L | - | D | e | v | �         #
-- #       ������ By Crystofher Lins.�        #
--- #-=--==-=-=-=-=-=-=--==-=-=-=-=-=-=-==-=-=# 
CREATE DATABASE SisLoja;
GO
USE SisLoja;
GO

IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'Clientes') AND NAME = N'ID')
BEGIN
CREATE TABLE Clientes (
ID INT IDENTITY PRIMARY KEY NOT NULL,
Data DATETIME,
Nome VARCHAR(50) NOT NULL,
CPF VARCHAR(18),
Rua VARCHAR(100),
Bairro VARCHAR(50),
Cidade VARCHAR(50),
Cep VARCHAR(9),
Estado VARCHAR(50),
Telefone VARCHAR(15) NOT NULL,
Whatsapp VARCHAR(15),
Email VARCHAR(50),
EstaAtivo CHAR(1) NOT NULL DEFAULT(1)
);
END
GO
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'Produtos') AND NAME = N'ID')
BEGIN
CREATE TABLE Produtos (
ID INT IDENTITY PRIMARY KEY NOT NULL,
CodBar VARCHAR(13),
QrCode VARCHAR (13),
Referencia VARCHAR(13),
Img VARCHAR(200),
Nome VARCHAR(50) NOT NULL,
Modelo VARCHAR(50),
Cor VARCHAR(25),
EstoqueMin INT DEFAULT(0),
PrecoVenda DECIMAL(10,2) NOT NULL,
EstaAtivo CHAR(1) NOT NULL DEFAULT(1)
)
END
GO
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'Estoque') AND NAME = N'ID')
BEGIN
CREATE TABLE Estoque (
ID INT IDENTITY PRIMARY KEY NOT NULL,
ProdID INT FOREIGN KEY REFERENCES Produtos(ID) NOT NULL,
QrCode VARCHAR(13),
Cor VARCHAR(25),
Num18 INT DEFAULT(0),
Num19 INT DEFAULT(0),
Num20 INT DEFAULT(0),
Num21 INT DEFAULT(0),
Num22 INT DEFAULT(0),
Num23 INT DEFAULT(0),
Num24 INT DEFAULT(0),
Num25 INT DEFAULT(0),
Num26 INT DEFAULT(0),
Num27 INT DEFAULT(0),
Num28 INT DEFAULT(0),
Num29 INT DEFAULT(0),
Num30 INT DEFAULT(0),
Num31 INT DEFAULT(0),
Num32 INT DEFAULT(0),
Num33 INT DEFAULT(0),
Num34 INT DEFAULT(0),
Num35 INT DEFAULT(0),
Num36 INT DEFAULT(0),
Num37 INT DEFAULT(0),
Num38 INT DEFAULT(0),
Num39 INT DEFAULT(0),
Num40 INT DEFAULT(0),
Num41 INT DEFAULT(0),
Num42 INT DEFAULT(0),
Num43 INT DEFAULT(0),
Num44 INT DEFAULT(0) 
)
END
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'Entradas') AND NAME = N'ID')
BEGIN
CREATE TABLE Entradas(
ID INT IDENTITY PRIMARY KEY NOT NULL,
ProdID INT FOREIGN KEY REFERENCES Produtos(ID) NOT NULL,
Data DATETIME,
Qtd VARCHAR(300) NOT NULL,
Preco DECIMAL(10,2) NOT NULL
)
END

SELECT * FROM Entradas;
SELECT * FROM Produtos;
SELECT * FROM Estoque;
