CREATE DATABASE SisLoja;
GO
USE SisLoja;
GO
CREATE TABLE Clientes (
ID INT IDENTITY PRIMARY KEY NOT NULL,
Data DATETIME,
Nome VARCHAR(50) NOT NULL,
CPF VARCHAR(18),
Rua VARCHAR(100),
Bairro VARCHAR(50),
Cidade VARCHAR(50),
Cep VARCHAR(9),
Estado VARCHAR(50),
Telefone VARCHAR(15) NOT NULL,
Whatsapp VARCHAR(15),
Email VARCHAR(50),
EstaAtivo CHAR(1) NOT NULL DEFAULT(1)
);
