--- #=-==-=--=-=-==-=-=--=-=-=-=-=-=-=-==-=-=-#
-- #          <SisLoja - DataBase>             #
-- #    Copyright (C) <2023-2023> <CL-Dev>     #
-- #		                                   #
-- #       | C | L | - | D | e | v | �         #
-- #       ������ By Crystofher Lins.�        #
--- #-=--==-=-=-=-=-=-=--==-=-=-=-=-=-=-==-=-=# 
CREATE DATABASE SisLoja;
GO
USE SisLoja;
GO

IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'Clientes') AND NAME = N'ID')
BEGIN
CREATE TABLE Clientes (
ID INT IDENTITY PRIMARY KEY NOT NULL,
Data DATETIME,
Nome VARCHAR(50) NOT NULL,
CPF VARCHAR(18),
Rua VARCHAR(100),
Bairro VARCHAR(50),
Cidade VARCHAR(50),
Cep VARCHAR(9),
Estado VARCHAR(50),
Telefone VARCHAR(15) NOT NULL,
Whatsapp VARCHAR(15),
Email VARCHAR(50),
EstaAtivo CHAR(1) NOT NULL DEFAULT(1)
);
INSERT INTO Clientes(Nome,Telefone) Values('Não Informado',00000);
END
GO
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'Produtos') AND NAME = N'ID')
BEGIN
CREATE TABLE Produtos (
ID INT IDENTITY PRIMARY KEY NOT NULL,
CodBar VARCHAR(13),
QrCode VARCHAR (13),
Referencia VARCHAR(13),
Img VARCHAR(200),
Nome VARCHAR(50) NOT NULL,
Modelo VARCHAR(50),
Cor VARCHAR(25),
EstoqueMin INT DEFAULT(0),
PrecoVenda DECIMAL(10,2) NOT NULL,
EstaAtivo CHAR(1) NOT NULL DEFAULT(1)
)
END
GO
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'Estoque') AND NAME = N'ID')
BEGIN
CREATE TABLE Estoque (
ID INT IDENTITY PRIMARY KEY NOT NULL,
ProdID INT FOREIGN KEY REFERENCES Produtos(ID) NOT NULL,
QrCode VARCHAR(13),
Cor VARCHAR(25),
Num18 INT DEFAULT(0),
Num19 INT DEFAULT(0),
Num20 INT DEFAULT(0),
Num21 INT DEFAULT(0),
Num22 INT DEFAULT(0),
Num23 INT DEFAULT(0),
Num24 INT DEFAULT(0),
Num25 INT DEFAULT(0),
Num26 INT DEFAULT(0),
Num27 INT DEFAULT(0),
Num28 INT DEFAULT(0),
Num29 INT DEFAULT(0),
Num30 INT DEFAULT(0),
Num31 INT DEFAULT(0),
Num32 INT DEFAULT(0),
Num33 INT DEFAULT(0),
Num34 INT DEFAULT(0),
Num35 INT DEFAULT(0),
Num36 INT DEFAULT(0),
Num37 INT DEFAULT(0),
Num38 INT DEFAULT(0),
Num39 INT DEFAULT(0),
Num40 INT DEFAULT(0),
Num41 INT DEFAULT(0),
Num42 INT DEFAULT(0),
Num43 INT DEFAULT(0),
Num44 INT DEFAULT(0) 
)
END
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'Entradas') AND NAME = N'ID')
BEGIN
CREATE TABLE Entradas(
ID INT IDENTITY PRIMARY KEY NOT NULL,
ProdID INT FOREIGN KEY REFERENCES Produtos(ID) NOT NULL,
Data DATETIME,
Qtd VARCHAR(300) NOT NULL,
Preco DECIMAL(10,2) NOT NULL
)
END
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'Vendas') AND NAME = N'ID')
BEGIN
CREATE TABLE Vendas(
ID INT PRIMARY KEY NOT NULL,
Data DATETIME,
ClienteID INT FOREIGN KEY REFERENCES Clientes(ID) DEFAULT(1),
TipoPagamento INT,
ValorVenda DECIMAL(10,2) NOT NULL DEFAULT(0),
ValorPago DECIMAL(10,2) NOT NULL DEFAULT(0),
Descontos DECIMAL(10,2) NOT NULL DEFAULT(0),
VendaCanceleda INT DEFAULT(0)
)
INSERT INTO Vendas (ID) Values(1234);
END
IF NOT EXISTS (SELECT 1 FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(N'ItemsVenda') AND NAME = N'ID')
BEGIN
CREATE TABLE ItemsVenda(
ID INT IDENTITY PRIMARY KEY NOT NULL,
VendaID INT FOREIGN KEY REFERENCES Vendas(ID),
ProdID INT FOREIGN KEY REFERENCES Produtos(ID),
Num INT,
Qtd INT
)
END

SELECT * FROM Clientes;
SELECT * FROM Entradas;
SELECT * FROM Produtos;
SELECT * FROM Estoque;
SELECT * FROM Vendas;
SELECT * FROM ItemsVenda;


UPDATE Vendas SET ClienteID = 1 WHERE ID = 1251;
SELECT * FROM Vendas;


SELECT TOP 1 ID FROM Vendas ORDER BY ID DESC;

ALTER TABLE Vendas ADD VendaCancelada INT DEFAULT(0);
UPDATE Vendas SET VendaCancelada = 0 WHERE ID = 1251;

INSERT INTO Produtos (Nome,PrecoVenda) VALUES('para excluir',10);

SELECT p.Img, p.CodBar, p.QrCode, p.Referencia, p.Nome, p.Modelo, p.Cor, p.EstoqueMin, p.PrecoVenda,e.Num44,e.Num43,e.Num42,e.Num41,e.Num40,e.Num39,e.Num38,e.Num37,e.Num36,
e.Num35,e.Num34,e.Num33,e.Num32,e.Num31,e.Num30,e.Num29, e.Num28,e.Num27,e.Num26,e.Num25,e.Num24,e.Num23,e.Num22,e.Num21,e.Num20,e.Num19,e.Num18 FROM Produtos p, Estoque e 
WHERE p.Codbar = '7890333910205' AND p.ID = e.ProdID AND p.EstaAtivo = 1


